-- Eliminar la tabla ODONTOLOGOS si existe
DROP TABLE IF EXISTS ODONTOLOGOS;

-- Crear la tabla ODONTOLOGOS
CREATE TABLE ODONTOLOGOS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MATRICULA INT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL
);

-- Eliminar la tabla DOMICILIOS si existe
DROP TABLE IF EXISTS DOMICILIOS;

-- Crear la tabla DOMICILIOS
CREATE TABLE DOMICILIOS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CALLE VARCHAR(50) NOT NULL,
    NUMERO INT NOT NULL,
    LOCALIDAD VARCHAR(50) NOT NULL,
    PROVINCIA VARCHAR(50) NOT NULL
);

-- Eliminar la tabla PACIENTES si existe
DROP TABLE IF EXISTS PACIENTES;

-- Crear la tabla PACIENTES
CREATE TABLE PACIENTES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    DNI INT NOT NULL,
    FECHA DATE NOT NULL,
    DOMICILIO_ID BIGINT  -- Cambiado de LONG a BIGINT
);

-- Insertar datos de prueba en la tabla DOMICILIOS
INSERT INTO DOMICILIOS (CALLE, NUMERO, LOCALIDAD, PROVINCIA)
VALUES 
('Av Siempre Viva', 742, 'Springfield', 'Massachusetts'),
('Calle Wallaby', 42, 'Sydney', 'Nueva Gales del Sur');

-- Insertar datos de prueba en la tabla PACIENTES
INSERT INTO PACIENTES (NOMBRE, APELLIDO, DNI, FECHA, DOMICILIO_ID)
VALUES 
('Emiliano', 'Celli', 35464856, '2023-05-24', 1),
('Pablo', 'Clemente', 3548546, '2023-05-24', 2);
